# Generated by Django 3.1.5 on 2021-01-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=1500, unique=True, verbose_name='slug'),
        ),
    ]
