# Generated by Django 3.1.5 on 2021-01-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210115_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500, verbose_name='Name')),
                ('books', models.ManyToManyField(to='books.Book')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
