# Generated by Django 3.1.5 on 2021-01-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20210129_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='illustrator',
        ),
        migrations.AddField(
            model_name='book',
            name='illustrator_1',
            field=models.ManyToManyField(blank=True, null=True, related_name='illustrator_1', to='books.Illustrator'),
        ),
        migrations.AddField(
            model_name='book',
            name='illustrator_2',
            field=models.ManyToManyField(blank=True, null=True, related_name='illustrator_2', to='books.Illustrator'),
        ),
    ]
