# Generated by Django 3.1.5 on 2021-01-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20210129_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='illustrator_1',
        ),
        migrations.AddField(
            model_name='book',
            name='illustrator_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illustrator_1', to='books.illustrator'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='illustrator_2',
        ),
        migrations.AddField(
            model_name='book',
            name='illustrator_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illustrator_2', to='books.illustrator'),
        ),
    ]
