# Generated by Django 3.1.5 on 2021-01-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20210129_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
    ]
