# Generated by Django 3.1.5 on 2021-01-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20210130_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_published_year', models.IntegerField(blank=True, null=True)),
                ('last_circulation_year', models.IntegerField(blank=True, null=True)),
                ('last_circulation_number', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market', to='books.isbn')),
            ],
        ),
    ]
