# Generated by Django 3.1.5 on 2021-01-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_market'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='last_circulation_number',
            new_name='last_circulation',
        ),
        migrations.RemoveField(
            model_name='market',
            name='last_circulation_year',
        ),
    ]
