# Generated by Django 3.1.5 on 2021-01-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20210130_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='isbn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market', to='books.isbn'),
        ),
    ]
