# Generated by Django 3.1.5 on 2021-01-30 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20210130_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.OneToOneField(default=111111, on_delete=django.db.models.deletion.CASCADE, related_name='isbn', to='books.isbn'),
        ),
    ]
