# Generated by Django 3.1.5 on 2021-01-30 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20210130_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isbn', to='books.isbn'),
        ),
    ]
