# Generated by Django 3.1.5 on 2021-01-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='latin_name',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
