# Generated by Django 3.1.5 on 2021-02-04 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_auto_20210130_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Shoora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=1000, null='True')),
                ('category', models.CharField(blank=True, max_length=1000, null='True')),
                ('function', models.CharField(blank=True, max_length=1000, null='True')),
                ('property', models.CharField(blank=True, max_length=1000, null='True')),
                ('satiric', models.BooleanField(default=False)),
                ('main_character', models.CharField(choices=[('human', 'Human'), ('animal', 'Animal'), ('other', 'Other')], default='human', max_length=200)),
                ('main_character_description', models.TextField(blank=True, null=True)),
                ('pov', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Point of view')),
                ('events_place', models.CharField(blank=True, max_length=1500, null=True)),
                ('child_special_need', models.CharField(blank=True, max_length=1500, null=True)),
                ('genre', models.CharField(blank=True, max_length=1000, null=True)),
                ('genre_descriptive', models.CharField(blank=True, max_length=2500, null=True)),
                ('age_from', models.IntegerField(blank=True, null=True)),
                ('age_to', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=1500, null=True)),
                ('book_latin_name', models.CharField(blank=True, max_length=1500, null=True)),
                ('author_latin_name', models.CharField(blank=True, max_length=1500, null=True)),
                ('language', models.CharField(blank=True, max_length=1500, null=True)),
                ('nationality', models.CharField(blank=True, max_length=1500, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('other_translation', models.BooleanField(default=False)),
                ('copyright', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('book_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_group', to='books.bookgroup')),
                ('isbn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shoora', to='books.isbn')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='books.shoora')),
            ],
        ),
    ]
