# Generated by Django 3.1.5 on 2021-02-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_bookgroup_content_shoora'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='latin_name',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
