# Generated by Django 3.1.5 on 2021-03-24 06:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_auto_20210324_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='critique',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='shoora',
            name='main_character_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
